### ISSUE TITLE
Azure File Copy Extended unable set Additional Arguments

### ISSUE THREAD

**Issue by doggy8088** [geeklearningio/gl-vsts-tasks-azure#57]
I'm using Azure Pipelines. I'd like to append `/SetContentType` to the AzCopy command so I configured Additional Arguments field. Here is my config:

![image](https://user-images.githubusercontent.com/88981/130341376-63804067-2268-4c7c-a616-e997e7db1353.png)

Here is the YAML version:

```yaml
steps:
- task: geeklearningio.gl-vsts-tasks-azure.az-copy-task.AzCopy@1
  displayName: 'Copy files from or to Azure Storage'
  inputs:
    SourceKind: FileSystem
    SourcePath: '$(System.DefaultWorkingDirectory)/_QA-CI/drop/site'
    DestinationConnectedServiceName: 'Microsoft Azure Sponsorship'
    DestinationAccount: docs
    DestinationObject: site
    Recursive: true
    ExcludeNewer: false
    ExcludeOlder: false
    Arguments: /SetContentType
```

Here is the log. I can't see `/SetContentType` in the command:

```sh
2021-08-22T03:24:15.1293251Z [command]C:\agents\2.190.0\externals\azcopy\azcopy.exe /Source:D:\a\r1\a\_QA-CI\drop\site /Dest:https://mystor.blob.core.windows.net/site /DestKey:****** /S /Y
```

I saw the source. It seems okay. I don't know why I can't add Additional Arguments to the command.

https://github.com/geeklearningio/gl-vsts-tasks-azure/blob/5da85062a3925111f3b87469220fe04ed3e3956c/Tasks/AzCopy/azCopy.ts#L196-L198

I already tried many ways. I never have a chance to add additional arguments to the AzCopy command.

Is this a bug or what's missing from me?
